### ISSUE TITLE
Get travis working

### ISSUE THREAD

**Issue by davisg123** [ECE-458-Resource-Manager/ResourceManager#1]
Travis-ci runs tests each build, it says we can use a meteor testing framework called laika.  Should try to get that working.

Using worker: worker-linux-docker-c88af031.prod.travis-ci.org:travis-linux-8

Build system information
Build language: node_js
Build group: stable
Build dist: precise
Build image provisioning date and time
Thu Feb  5 15:09:33 UTC 2015
Operating System Details
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:    12.04
Codename:   precise
Linux Version
3.13.0-29-generic
Cookbooks Version
a68419e https://github.com/travis-ci/travis-cookbooks/tree/a68419e
GCC version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

LLVM version
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Pre-installed Ruby versions
ruby-1.9.3-p551
Pre-installed Node.js versions
v0.10.36
Pre-installed Go versions
1.4.1
Redis version
redis-server 2.8.19
riak version
2.0.2
MongoDB version
MongoDB 2.4.12
CouchDB version
couchdb 1.6.1
Neo4j version
1.9.4
RabbitMQ Version
3.4.3
ElasticSearch version
1.4.0
Installed Sphinx versions
2.0.10
2.1.9
2.2.6
Default Sphinx version
2.2.6
Installed Firefox version
firefox 31.0esr
PhantomJS version
1.9.8
ant -version
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_76, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.13.0-29-generic", arch: "amd64", family: "unix"

$ git clone --depth=50 --branch=master https://github.com/ECE-458-Resource-Manager/ResourceManager.git ECE-458-Resource-Manager/ResourceManager
Cloning into 'ECE-458-Resource-Manager/ResourceManager'...
remote: Counting objects: 37, done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 37 (delta 8), reused 26 (delta 2), pack-reused 0
Unpacking objects: 100% (37/37), done.
Checking connectivity... done.
$ cd ECE-458-Resource-Manager/ResourceManager
$ git checkout -qf e5e36caf26dae88b930551d78b4492d9c06779f7
$ sudo service mongodb start
[ OK ]

This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
If you require sudo, add 'sudo: required' to your .travis.yml
See https://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.

Setting environment variables from .travis.yml
$ export LAIKA_OPTIONS="-t 5000"

$ nvm install 0.12
###### ################################################################## 100.0%

Now using node v0.12.9
$ node --version
v0.12.9
$ npm --version
2.14.9
$ nvm --version
0.23.3
$ curl -L https://raw.githubusercontent.com/arunoda/travis-ci-laika/master/configure.sh | /bin/sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   250  100   250    0     0   3502      0 --:--:-- --:--:-- --:--:--  4464
--2016-01-16 16:17:59--  https://raw.github.com/arunoda/travis-ci-laika/master/Makefile
Resolving raw.github.com (raw.github.com)... 199.27.76.133
Connecting to raw.github.com (raw.github.com)|199.27.76.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/arunoda/travis-ci-laika/master/Makefile [following]
--2016-01-16 16:18:00--  https://raw.githubusercontent.com/arunoda/travis-ci-laika/master/Makefile
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.27.76.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.27.76.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 42 [text/plain]
Saving to: `Makefile'

100%[======================================>] 42          --.-K/s   in 0s      

2016-01-16 16:18:00 (19.4 MB/s) - `Makefile' saved [42/42]

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6674    0  6674    0     0  38523      0 --:--:-- --:--:-- --:--:-- 40695
Downloading Meteor distribution
###### ################################################################## 100.0%

Meteor 1.2.1 has been installed in your home directory (~/.meteor).
Writing a launcher script to /usr/local/bin/meteor for your convenience.
This may prompt for your password.
sudo: must be setuid root

Couldn't write the launcher script. Please either:

  (1) Run the following as root:
        cp "/home/travis/.meteor/packages/meteor-tool/1.1.10/mt-os.linux.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor
  (2) Add "$HOME/.meteor" to your path, or
  (3) Rerun this command to try again.

Then to get started, take a look at 'meteor --help' or see the docs at
docs.meteor.com.
/home/travis/.nvm/versions/node/v0.12.9/bin/mrt -> /home/travis/.nvm/versions/node/v0.12.9/lib/node_modules/meteorite/bin/mrt.js

> meteorite@0.9.3 postinstall /home/travis/.nvm/versions/node/v0.12.9/lib/node_modules/meteorite
> sh ./completions/postinstall.sh

meteorite@0.9.3 /home/travis/.nvm/versions/node/v0.12.9/lib/node_modules/meteorite
├── rolling_timeout_exec@0.0.1
├── colors@0.6.0-1
├── wrench@1.3.9
├── async@0.2.9
├── underscore@1.3.3
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── ddp@0.4.6 (node-srp@0.0.1, meteor-ejson@0.6.3, faye-websocket@0.7.3)
├── fstream@1.0.8 (inherits@2.0.1, graceful-fs@4.1.2, mkdirp@0.5.1, rimraf@2.5.0)
└── prompt@0.2.11 (revalidator@0.1.8, pkginfo@0.3.1, read@1.0.7, utile@0.2.1, winston@0.6.2)

> fibers@1.0.8 install /home/travis/.nvm/versions/node/v0.12.9/lib/node_modules/laika/node_modules/fibers
> node build.js || nodejs build.js

make: Entering directory `/home/travis/.nvm/versions/node/v0.12.9/lib/node_modules/laika/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/obj.target/fibers.node
  COPY Release/fibers.node
make: Leaving directory`/home/travis/.nvm/versions/node/v0.12.9/lib/node_modules/laika/node_modules/fibers/build'
Installed in `/home/travis/.nvm/versions/node/v0.12.9/lib/node_modules/laika/node_modules/fibers/bin/linux-x64-v8-3.28/fibers.node`

> kerberos@0.0.3 install /home/travis/.nvm/versions/node/v0.12.9/lib/node_modules/laika/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/travis/.nvm/versions/node/v0.12.9/lib/node_modules/laika/node_modules/mongodb/node_modules/kerberos/build'
  SOLINK_MODULE(target) Release/obj.target/kerberos.node
  COPY Release/kerberos.node
make: Leaving directory`/home/travis/.nvm/versions/node/v0.12.9/lib/node_modules/laika/node_modules/mongodb/node_modules/kerberos/build'

> bson@0.2.2 install /home/travis/.nvm/versions/node/v0.12.9/lib/node_modules/laika/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/travis/.nvm/versions/node/v0.12.9/lib/node_modules/laika/node_modules/mongodb/node_modules/bson/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
make: Leaving directory`/home/travis/.nvm/versions/node/v0.12.9/lib/node_modules/laika/node_modules/mongodb/node_modules/bson/build'
/home/travis/.nvm/versions/node/v0.12.9/bin/laika -> /home/travis/.nvm/versions/node/v0.12.9/lib/node_modules/laika/bin/laika
laika@0.3.10 /home/travis/.nvm/versions/node/v0.12.9/lib/node_modules/laika
├── commander@2.0.0
├── colors@0.6.2
├── qbox@0.1.7
├── mkdirp@0.3.5
├── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)
├── mocha@1.16.2 (diff@1.0.7, growl@1.7.0, debug@2.2.0, jade@0.26.3)
├── node-phantom@0.2.5 (socket.io@1.4.4)
├── handlebars@1.0.12 (optimist@0.3.7, uglify-js@2.3.6)
├── fibers@1.0.8
└── mongodb@1.3.15 (kerberos@0.0.3, bson@0.2.2)
$ make test
laika $LAIKA_OPTIONS

  injecting laika...
  loading phantomjs...
  cleaning up injected code

/home/travis/.nvm/versions/node/v0.12.9/lib/node_modules/laika/lib/app.js:124
    if(err) throw err;
                  ^
Error: spawn meteor ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1054:32)
    at child_process.js:1145:20
    at process._tickCallback (node.js:355:11)
make: **\* [test] Error 1

The command "make test" exited with 2.

Done. Your build exited with 1.

**Comment by davisg123** [comment]
https://github.com/ECE-458-Resource-Manager/ResourceManager/commit/368d4cb0acfa6d8f9b8b6d99daf777c9222f9a09
